apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-main-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri = "/") {
        return 301 /main;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: cafekec.shop
    http:
      paths:
      - path: /main(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: web-v2-service
            port:
              number: 80
      - path: /api/main/weather(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: kma-api
            port:
              number: 8080
      - path: /api/main/energy(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: energy-api
            port:
              number: 8000
      - path: /healthz/global-status
        pathType: Exact
        backend:
          service:
            name: energy-api
            port:
              number: 8000